### ISSUE TITLE
RealUrl not really working

### ISSUE THREAD

**Issue by sdesign6** [lochmueller/calendarize#267]
I have some issues of with RealUrl and I just can't get it to work.
TYPO3 is 8.7.20, realurl 2.4.0, calendarize 4.0.1
There's no realurl masking, even if I enabled automatic configuration.

**Comment by lochmueller** [comment]
Did you see: \HDNET\Calendarize\Hooks\RealurlConfiguration

The is only for the "tx_realurl_autoconfgen" realurl context. most installation use a manually configuration. So you have to add the "postVarSets" configuration manually to your realurl configuration.

Regards,
Tim

**Comment by sdesign6** [comment]
thanks for your reply. I did see \HDNET\Calendarize\Hooks\RealurlConfiguration and implemented it first in my manual configuration as described. Now I tried it with the RealUrl autoconfig and I am testing with this option right now, but now I'm getting the following error:

Oops, an error occurred!
The given alias '`tx_calendarize_domain_model_index`' is not part of any FROM or JOIN clause table. The currently registered aliases are: `tx_realurl_uniqalias`.

Regards
Sven

**Comment by lochmueller** [comment]
Seems to be a problem in the doctrine migration in:
https://github.com/lochmueller/calendarize/blob/master/Classes/Service/Url/RealUrl.php#L67

I/We will check this in the next days...

**Comment by sdesign6** [comment]
Thank you. Could you take a look at the issue?

**Comment by lochmueller** [comment]
No... many tasks in the lasst days. I will send you feedback, if the problem is fixed. But it seams, that is exactly this line https://github.com/lochmueller/calendarize/blob/master/Classes/Service/Url/RealUrl.php#L67 and the migration von old TYPO3_DB to the new Doctrine DBAL.
Regards,
Tim

**Comment by cnoelker** [comment]
Actually, not only line 67 is the problem, but also the missing literal() for the eq() comparisons in the where clauses. Fix:
Change in cleanupOldLinks():
        $q->select('u.uid')
        ->from('tx_realurl_uniqalias','u')
        ->leftJoin('u', 'tx_calendarize_domain_model_index', 'i', 'u.value_id = i.uid')
        ->where(
        		$q->expr()->andX(
        				$q->expr()->isNull('i.uid'),
        				$q->expr()->eq('u.tablename', $q->expr()->literal("tx_calendarize_domain_model_index"))
        				)
        		);

And add a $q->expr()->literal() like this:
$q->expr()->eq('tablename', $q->expr()->literal(IndexerService::TABLE_NAME)),

**Comment by lochmueller** [comment]
Hey @cnoelker Thanks for the hint. THe problem is fixed in the current master. Regards, Tim

**Comment by sdesign6** [comment]
Still getting in error:
Oops, an error occurred!
An exception occurred while executing 'SELECT `uid` FROM `tx_realurl_uniqalias` `u` LEFT JOIN `tx_calendarize_domain_model_index` `i` ON u.value_id = i.uid WHERE (`i`.`uid` IS NULL) AND (`u`.`tablename` = 'tx_calendarize_domain_model_index') AND ((`i`.`deleted` = 0) AND (`i`.`hidden` = 0) AND (`i`.`starttime` <= 1543227960) AND ((`i`.`endtime` = 0) OR (`i`.`endtime` > 1543227960)))': Column 'uid' in field list is ambiguous

**Comment by lochmueller** [comment]
Hey @sdesign6 
Fixed in current master. Feel free to send pull requests for further changes...
Regards,
Tim

**Comment by sdesign6** [comment]
Sry, just can help you with testing and bug reporting. Next error after your fix:
Oops, an error occurred!
An exception occurred while executing 'SELECT `value_id` FROM `tx_realurl_uniqalias` WHERE (`tablename` = tx_calendarize_domain_model_index) AND (`value_id` = ?)' with params [77019]: Unknown column 'tx_calendarize_domain_model_index' in 'where clause'

**Comment by lochmueller** [comment]
Hey @sdesign6 
I added two more literal calls.
Thanks,
Tim

**Comment by sdesign6** [comment]
Hi Tim, it's working now! Thx.
