### ISSUE TITLE
[BUG] Event disappears if event is saved/created at start_date

### ISSUE THREAD

**Issue by c2po** [lochmueller/calendarize#28]
Hi,
in version 1.7.1 and master an event disappears if it is saved at the same day of the event (start_date). Calendarize Information and the list view do not show events on start_date. An entry is created in tx_calendarize_domain_model_index. The day view shows these events correctly.

**Comment by lochmueller** [comment]
Hey @c2po 
I try to rebuild your problem... either the problem is fixed or I do not understand you description...
Regards,
Tim

**Comment by c2po** [comment]
Hi Tim,
the problem is not fixed, sorry. I have a setup with calendarize_news 0.3.1. One page with two plugins: one in **mode Month**, one in mode **List only**.

Please create an event with the start_date of today (today I entered: 17-12-2015).

**Have a look at wrong results at "Calendarize (Information - Save to refresh...)":**
There is/are **1 item/items** in the index of the current record. The next 10 events (incl. today) are 
    **No events**

**With some date in the future I get a correct result:**
There is/are 1 item/items in the index of the current record. The next 10 events (incl. today) are     18.12.2015 - 18.12.2015 (15:00 - 00:00)

I tried this with old version 802947fb3b87a3d14228cc9ad77ef5987234cdfa and today version 877c3e50f25accb63b5e806467b8606b8589ab07 from 15.12.15 09:27.

The above mentioned problem with the list only mode also remains.

**Comment by lochmueller** [comment]
Hey @c2po 
The problem you described is a Backend problem? So the list/month view in the frontend are irrelevant, right? The indexing process is a backend process.... I create a event and see the item in the list (screenshot). Do you also use TYPO3_CONF_VARS|SYS|phpTimeZone => 'UTC'?
![test](https://cloud.githubusercontent.com/assets/3907126/11877106/78f6d0dc-a4ed-11e5-8370-e4039478c41b.png)

**Comment by c2po** [comment]
Hi Tim,
it is about frontend & backend problems.

Actually I have **[SYS][phpTimeZone] = Europe/Berlin** and **[SYS][serverTimeZone] = 1**.

Both problems do not occur with your (wrong?) setting [SYS][phpTimeZone] = UTC.

**Comment by lochmueller** [comment]
Ahh... I saw that [SYS][phpTimeZone] is not used in the core anymore (TYPO3 7.x). But nevertheless, the output in the frontend and backend is right in my installation. I saw the event in month and list view...

**Comment by lochmueller** [comment]
Hey @c2po 
Any news on this topic? Should I take a look into your dev system? Otherwise I will close this issue, because it is not reproducible on my machines...
Regards,
Tim

**Comment by c2po** [comment]
Hi Tim,
this is a severe bug on 6.2 LTS systems with a timezone other than GMT. It is more severe than I assumed at the beginning because it is not necessary to edit at the same day.

Please do not close this issue!

Do you have a 6.2 LTS machine where this is not reproducable? I can reproduce this on two different machines. I will try to dig deeper in the beginning of the new year.

**Comment by lochmueller** [comment]
Hey @c2po 
I ran a test on a 6.2 LTS machine, with the same result. Backend and Frontend are in the right zone. I also set "[SYS][phpTimeZone] = Europe/Berlin and [SYS][serverTimeZone] = 1", but the result is still the same (also after creating a new event). I cannot rebuild the problem on my maschines...

I leave this issue open, if someone else fight against the same problem...

Regards,
Tim

**Comment by c2po** [comment]
Hi Tim,
today I installed the most actual version from here on one machine. After that both errors from above did not occure anymore. I had restored calendarize version 1.7.1 from TER and then both errors were back again. Your changes seem to have fixed the problem. Thank you!
At the weekend I will test the one machine.

**Comment by lochmueller** [comment]
Nice. I will close this issue... If there are still problem, please create a new one.

**Comment by c2po** [comment]
Hi Tim,
to be sure that an already created index is still valid with the new version I compared the entries in tx_calendarize_domain_model_index created by version 1.7.1 and 2.0.0. They are equal, so everything should be fine. 

(BTW: there should be a scheduler task which refreshes the index. I will create a new issue for that)

**Comment by lochmueller** [comment]
Hey @c2po 
A reindex scheduler task is already part of the extension. It is a ExtBase CommandController.
Regards,
Tim

**Comment by c2po** [comment]
Good to know :)  - I will not create an new issue for that ;)
